/**
 * Writes `generated/tokens.css` from `src/tokens.ts`.
 *
 * The stylesheet is generated rather than hand-kept so that the CSS and the
 * React Native theme cannot disagree: there is one list of values and two
 * renderings of it. The output is committed, so a `pnpm install` in a fresh
 * clone has a stylesheet before anything has been built, and CI re-runs this
 * to check the committed file still matches its source.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { toCss } from '../src/tokens.ts';

const out = join(dirname(fileURLToPath(import.meta.url)), '..', 'generated', 'tokens.css');
const banner = `/* Generated by packages/design/scripts/emit-css.ts. Do not edit.\n   Change packages/design/src/tokens.ts and run \`pnpm -F @playerone/design build:css\`. */\n\n`;
writeFileSync(out, banner + toCss(), 'utf8');
console.log(`wrote ${out}`);
