const en = {
  finalizing: 'Upload sent. Waiting for the server to save it…', refresh: 'Refresh clips',
  uploadTimeout: 'The upload timed out. Refresh your clips before retrying; the server may have saved it.',
  uploadUncertain: 'The connection was interrupted. Refresh your clips before retrying to check whether it was saved.',
  uploadCancelled: 'Upload stopped. Refresh your clips to check whether the server had already saved it.',
  title: 'Demo studio', intro: 'Upload a short clip, play it back, and try reviewing your own footage.',
  boundary: 'Demonstration only. These clips and decisions never enter the production review queue, earnings, or payments.',
  limits: 'MP4 or WebM · up to 20 MB per clip · 5 clips per account · automatically removed after 7 days.',
  choose: 'Choose footage', upload: 'Upload demo clip', uploading: 'Uploading', cancel: 'Cancel upload',
  list: 'Your demo clips', empty: 'No demo clips yet. Choose a video to begin.', loading: 'Loading your clips…',
  retry: 'Try again', preview: 'Uploaded clip preview', expires: 'Expires', delete: 'Delete clip', deleting: 'Deleting…',
  review: 'Try a review', verdict: 'Demo decision', good: 'Pass — demo', partial: 'Needs improvement — demo', bad: 'Reject — demo',
  note: 'Review notes', save: 'Save demo decision', saving: 'Saving…', saved: 'Demo decision saved',
  unreviewed: 'Not reviewed', reviewed: 'Demo decision recorded', denied: 'Sign in with an operator account to use the demo studio.',
  failed: 'This request could not finish. Try again.', playback: 'This browser cannot play this clip. Try an H.264 MP4 or a supported WebM file.',
  fileError: 'Choose an MP4 or WebM file between 1 byte and 20 MB.',
  showcase_owner_quota: 'Your five clip slots are full. Delete a clip before uploading another.',
  showcase_storage_quota: 'Demo storage is full. Delete an unused clip or try again later.',
  showcase_upload_busy: 'Other clips are uploading. Wait a few seconds and try again.',
  showcase_video_required: 'The file does not have an MP4 or WebM video header.',
  showcase_filename_invalid: 'Use a file name under 180 characters without slashes.',
  showcase_not_found: 'This clip expired or was deleted. Refresh your list.',
};
export const SHOWCASE_COPY: Record<'en' | 'vi' | 'zh', Record<keyof typeof en, string>> = {
  en,
  vi: {
    finalizing: 'Đã gửi video. Đang chờ máy chủ lưu…', refresh: 'Tải lại video',
    uploadTimeout: 'Tải lên quá thời gian chờ. Tải lại danh sách trước khi thử lại; máy chủ có thể đã lưu video.',
    uploadUncertain: 'Kết nối bị gián đoạn. Tải lại danh sách để kiểm tra video đã lưu chưa trước khi thử lại.',
    uploadCancelled: 'Đã dừng tải lên. Tải lại danh sách để kiểm tra máy chủ đã lưu video chưa.',
    title: 'Phòng thử nghiệm', intro: 'Tải lên một đoạn phim ngắn, xem lại và thử tự đánh giá cảnh quay của bạn.',
    boundary: 'Chỉ dùng để trình diễn. Video và quyết định tại đây không đi vào hàng đợi đánh giá thật, thu nhập hay thanh toán.',
    limits: 'MP4 hoặc WebM · tối đa 20 MB mỗi video · 5 video mỗi tài khoản · tự xóa sau 7 ngày.',
    choose: 'Chọn video', upload: 'Tải video thử nghiệm', uploading: 'Đang tải lên', cancel: 'Hủy tải lên',
    list: 'Video thử nghiệm của bạn', empty: 'Chưa có video thử nghiệm. Chọn video để bắt đầu.', loading: 'Đang tải danh sách…',
    retry: 'Thử lại', preview: 'Xem lại video đã tải', expires: 'Hết hạn', delete: 'Xóa video', deleting: 'Đang xóa…',
    review: 'Thử đánh giá', verdict: 'Quyết định thử nghiệm', good: 'Đạt — thử nghiệm', partial: 'Cần cải thiện — thử nghiệm', bad: 'Không đạt — thử nghiệm',
    note: 'Ghi chú đánh giá', save: 'Lưu quyết định thử nghiệm', saving: 'Đang lưu…', saved: 'Đã lưu quyết định thử nghiệm',
    unreviewed: 'Chưa đánh giá', reviewed: 'Đã ghi nhận quyết định thử nghiệm', denied: 'Đăng nhập bằng tài khoản nhân viên để dùng phòng thử nghiệm.',
    failed: 'Không hoàn tất được yêu cầu. Vui lòng thử lại.', playback: 'Trình duyệt không phát được video này. Hãy thử MP4 mã hóa H.264 hoặc WebM được hỗ trợ.',
    fileError: 'Chọn tệp MP4 hoặc WebM có dung lượng từ 1 byte đến 20 MB.',
    showcase_owner_quota: 'Đã đủ năm video. Xóa một video trước khi tải thêm.',
    showcase_storage_quota: 'Bộ nhớ trình diễn đã đầy. Xóa video không dùng hoặc thử lại sau.',
    showcase_upload_busy: 'Có video khác đang tải lên. Chờ vài giây rồi thử lại.',
    showcase_video_required: 'Tệp không có phần đầu video MP4 hoặc WebM hợp lệ.',
    showcase_filename_invalid: 'Tên tệp phải dưới 180 ký tự và không chứa dấu gạch chéo.',
    showcase_not_found: 'Video đã hết hạn hoặc bị xóa. Tải lại danh sách.',
  },
  zh: {
    finalizing: '视频已发送，正在等待服务器保存…', refresh: '刷新视频',
    uploadTimeout: '上传超时。重试前请刷新视频列表；服务器可能已保存视频。',
    uploadUncertain: '连接已中断。重试前请刷新列表，检查视频是否已保存。',
    uploadCancelled: '上传已停止。请刷新列表，检查服务器是否已保存视频。',
    title: '演示工作室', intro: '上传短视频、回放，并尝试自行审核自己的素材。',
    boundary: '仅用于演示。此处的视频和决定不会进入正式审核队列、收入或付款流程。',
    limits: 'MP4 或 WebM · 每个视频最多 20 MB · 每个账号 5 个视频 · 7 天后自动删除。',
    choose: '选择视频', upload: '上传演示视频', uploading: '正在上传', cancel: '取消上传',
    list: '你的演示视频', empty: '暂无演示视频。选择视频即可开始。', loading: '正在加载视频…',
    retry: '重试', preview: '已上传视频回放', expires: '到期时间', delete: '删除视频', deleting: '正在删除…',
    review: '尝试审核', verdict: '演示决定', good: '通过 — 演示', partial: '需要改进 — 演示', bad: '拒绝 — 演示',
    note: '审核备注', save: '保存演示决定', saving: '正在保存…', saved: '演示决定已保存',
    unreviewed: '尚未审核', reviewed: '已记录演示决定', denied: '请使用操作员账号登录演示工作室。',
    failed: '未能完成请求，请重试。', playback: '此浏览器无法播放该视频，请尝试 H.264 MP4 或受支持的 WebM 文件。',
    fileError: '请选择大小为 1 字节至 20 MB 的 MP4 或 WebM 文件。',
    showcase_owner_quota: '已达到五个视频的限制，请先删除一个视频。',
    showcase_storage_quota: '演示存储已满，请删除不用的视频或稍后再试。',
    showcase_upload_busy: '其他视频正在上传，请稍候重试。',
    showcase_video_required: '该文件没有有效的 MP4 或 WebM 视频头。',
    showcase_filename_invalid: '文件名须少于 180 个字符，且不能包含斜杠。',
    showcase_not_found: '视频已到期或被删除，请刷新列表。',
  },
};
