import {withBrowser,newPage} from './browser.mjs';
import {writeFileSync} from 'node:fs';
const BASE='http://127.0.0.1:5190',OUT='scratchpad/qa/showcase-independent',out={fixtureOnly:true};
await withBrowser(async browser=>{
const {context,page}=await newPage(browser,{viewport:{width:375,height:812}});
await context.route('**/*',route=>{const p=new URL(route.request().url()).pathname;if(p==='/whoami')return route.fulfill({json:{role:'operator'}});if(p.startsWith('/api/')||p.startsWith('/reference')||p.startsWith('/handovers')||p.startsWith('/upload-batches'))return route.fulfill({status:503,json:{reason:'qa_fixture_unavailable',ref:'QA-FIXTURE'}});return route.continue();});
await page.goto(`${BASE}/review`);await page.waitForSelector('.ops-shell');await page.evaluate(()=>{window.__qaKeys=[];window.addEventListener('keydown',e=>window.__qaKeys.push(e.key));});await page.locator('button[aria-controls="workspace-navigation"]').click();await page.locator('#workspace-navigation a').first().focus();for(const key of ['ArrowLeft','ArrowRight','1','2','3','Space','Escape'])await page.keyboard.press(key);out.reviewKeysReachingWindow=await page.evaluate(()=>window.__qaKeys);out.reviewClosed=await page.locator('#workspace-navigation').evaluate(e=>!e.open);
await page.setViewportSize({width:1440,height:900});out.routes=[];
for(const path of ['/','/counter','/review','/episodes','/settle','/backoffice','/pipeline']){await page.goto(`${BASE}${path}`);await page.waitForSelector('.ops-shell');out.routes.push({path,current:await page.locator('.ops-shell-nav a[aria-current="page"]').getAttribute('href'),overflow:await page.evaluate(()=>Math.max(0,document.documentElement.scrollWidth-innerWidth))});}
await page.goto(`${BASE}/`);await page.waitForTimeout(8500);out.homeText=await page.locator('#workspace').innerText();await page.screenshot({path:`${OUT}/shell-unavailable-1440.png`});await context.close();
const login=await newPage(browser,{viewport:{width:375,height:600}});await login.context.route('**/*.mp4',r=>r.abort());await login.page.goto(`${BASE}/login`);await login.page.locator('.ops-login-film').scrollIntoViewIfNeeded();await login.page.locator('.ops-film-toggle').click();await login.page.waitForTimeout(500);out.filmFailure={visible:await login.page.locator('.ops-login-film [role="status"]').count(),inputsEnabled:await login.page.locator('.ops-credentials input').evaluateAll(es=>es.every(e=>!e.disabled)),submitEnabled:await login.page.locator('button[type="submit"]').isEnabled()};await login.context.close();
const demo=await newPage(browser,{viewport:{width:1440,height:900}});await demo.page.goto(`${BASE}/discover`);await demo.page.waitForSelector('.discover-page');out.demoAlignment=await demo.page.locator('.discover-demo-section .discover-section-heading').evaluate(e=>({align:getComputedStyle(e).alignItems,headingTop:e.querySelector('h2').getBoundingClientRect().top,copyTop:e.querySelector('.discover-lead').getBoundingClientRect().top}));await demo.page.locator('#demo').scrollIntoViewIfNeeded();await demo.page.screenshot({path:`${OUT}/demo-alignment-1440.png`});await demo.context.close();
});writeFileSync(`${OUT}/edge-results.json`,JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));

