/** Public story copy, Vietnamese first. Exact key parity is enforced by TypeScript. */
import {DISCOVER_HELP_COPY} from './discover-help-copy.ts';
import {DISCOVER_WARM_COPY} from './discover-warm-copy.ts';
const vi = {
  ...DISCOVER_HELP_COPY.vi,
  ...DISCOVER_WARM_COPY.vi,
  activityKitchen: 'Chuẩn bị bữa ăn', activityClothes: 'Sắp xếp quần áo', activityPacking: 'Đóng gói hàng', overlapShort: 'Phần chung',
  slogan: 'Việc quen thuộc. Góc nhìn mới.',
  heroA: 'Một ngày của bạn.', heroB: 'Một góc nhìn mới.',
  heroBody: 'Ghi lại hoạt động thường ngày với camera Ego. Nhận tiền cho số phút hữu ích được con người duyệt và chấp nhận.',
  explore: 'Khám phá bản demo', console: 'Đăng nhập console',
  skip: 'Bỏ qua phần mở đầu', scroll: 'Cuộn để khám phá',
  menu: 'Mở menu', close: 'Đóng menu', navigation: 'Điều hướng',
  work: 'Công việc', demo: 'Thử ứng dụng', camera: 'Camera Ego', review: 'Duyệt & thanh toán', questions: 'Câu hỏi',
  play: 'Phát video', pause: 'Tạm dừng video',
  filmLabel: 'Phim minh hoạ · góc nhìn bên ngoài, không phải hình ảnh do Ego ghi lại',
  filmError: 'Video chưa tải được. Bạn vẫn có thể khám phá bản demo bên dưới.',
  introTitle: 'Việc quen thuộc. Góc nhìn của bạn.',
  introBody: 'PlayerOne kết nối người thu thập tại Việt Nam với các nhiệm vụ ghi hình hoạt động thường ngày. VNG PT Lab xây dựng nền tảng; PaXini cung cấp camera Ego và duyệt dữ liệu.',
  demoTitle: 'Ngày của bạn. Một góc nhìn mới.',
  demoBody: 'Khám phá cách chọn nhiệm vụ và chuẩn bị phiên thu thập. Camera được bật bằng nút trên thiết bị — không phải trên điện thoại.',
  example: 'Bản demo tương tác · dữ liệu minh hoạ',
  exampleNote: 'Bản demo không nhận nhiệm vụ, tạo phiên hay ghi hình thật.',
  browse: 'Chọn nhiệm vụ', details: 'Chi tiết nhiệm vụ', prepare: 'Chuẩn bị phiên', ready: 'Sẵn sàng với Ego',
  taskKitchen: 'Sắp xếp quần áo', taskDesk: 'Sắp xếp bàn làm việc', taskShelf: 'Sắp xếp kệ hàng',
  preview: 'Ví dụ về hoạt động', tryClothes: 'Thử nhiệm vụ sắp xếp quần áo', previewNote: 'Bản demo tương tác sử dụng nhiệm vụ sắp xếp quần áo. Hoạt động này chỉ được giới thiệu để bạn tham khảo.',
  home: 'Tại nhà', office: 'Văn phòng', shop: 'Cửa hàng',
  taskHint: 'Xem hướng dẫn', taskDescription: 'Thực hiện công việc như thường ngày. Xem giới hạn và lưu ý riêng của nhiệm vụ trước khi nhận.',
  natural: 'Hoạt động tự nhiên', hands: 'Giữ thao tác trong khung hình', boundaries: 'Tuân theo hướng dẫn và giới hạn nhiệm vụ',
  prerequisites: 'Để nhận nhiệm vụ thật: hoàn tất các thoả thuận, đào tạo và vượt qua bài kiểm tra.',
  claim: 'Thử nhận nhiệm vụ', claimed: 'Đã chọn nhiệm vụ minh hoạ',
  device: 'Thiết bị cho phiên này', deviceExample: 'Ego · thiết bị minh hoạ đã liên kết',
  scenario: 'Bối cảnh', others: 'Có người khác có thể xuất hiện trong khung hình?', sensitive: 'Có thông tin nhạy cảm có thể xuất hiện?',
  choose: 'Chọn câu trả lời', yes: 'Có', no: 'Không',
  prepareAction: 'Chuẩn bị phiên minh hoạ', physical: 'Bắt đầu ghi bằng nút trên Ego.',
  physicalBody: 'Đeo camera trên trán, để mắt hoàn toàn thông thoáng. Ứng dụng chỉ chuẩn bị phiên; nút trên camera điều khiển việc ghi hình.',
  viewpoint: 'Khám phá góc nhìn thứ nhất', back: 'Quay lại', restart: 'Thử nhiệm vụ khác',
  povLabel: 'Góc nhìn thứ nhất được tạo bằng AI · minh hoạ',
  povAlt: 'Đôi tay thực hiện công việc thường ngày từ góc nhìn thứ nhất',
  workTitle: 'Người thu thập.',
  workBody: 'Tại nhà, văn phòng, cửa hàng hoặc kho. Mỗi lần ghi hình gắn với một nhiệm vụ đã nhận và hướng dẫn cụ thể.',
  imageLabel: 'Hình ảnh minh hoạ được tạo bằng AI; không phải người thu thập hay dữ liệu thực tế.', aiLabel: 'Minh hoạ AI',
  imageWide: 'Một người thực hiện công việc thường ngày trong ánh sáng ban ngày',
  imagePortrait: 'Một người đang làm việc tự nhiên với camera trên trán',
  imageDetail: 'Chi tiết bàn tay và vật dụng trong công việc thường ngày',
  cameraTitle: 'Đeo trên trán. Không che mắt.',
  cameraBody: 'Camera Ego được nền tảng cấp và liên kết với một người. Nút trên thiết bị bắt đầu và dừng ghi. Sau khi thu thập, mang thẻ nhớ đến điểm tải lên.',
  deviceMediaNote: 'Đoạn phim minh hoạ thiết bị đang được chỉnh để thể hiện đúng vị trí đeo trên trán.',
  deviceMediaLabel: 'Phim minh hoạ thiết bị',
  humanTitle: 'Việc thật. Người thật duyệt.',
  humanBody: 'Người duyệt xem từng bản ghi, xác định phần sử dụng được và nêu lý do cho phần còn lại. Thời gian ghi hình không tự động trở thành thời gian được trả tiền.',
  reviewExample: 'Minh hoạ các kết quả duyệt', good: 'Đạt', partial: 'Đạt một phần', reject: 'Không đạt',
  goodBody: 'Phần được duyệt và chấp nhận được tính vào thời gian hữu ích.',
  partialBody: 'Chỉ phần được duyệt và chấp nhận được tính; phần còn lại có lý do.',
  rejectBody: 'Phần không được chấp nhận không được tính tiền; người thu thập xem được lý do.',
  paymentTitle: 'Trả cho phút hữu ích được duyệt.',
  paymentBody: 'Thời gian đo từ dữ liệu là khoảng mà tất cả luồng ghi cùng bao phủ. Sau đó, quyết định của người duyệt xác định số phút hữu ích được chấp nhận để tính tiền theo đơn giá nhiệm vụ.',
  streamVideo: 'Video', streamAudio: 'Âm thanh', streamMotion: 'Chuyển động', overlap: 'Khoảng mọi luồng cùng bao phủ', diagram: 'Sơ đồ minh hoạ, không thể hiện thời lượng hay khoản tiền thực tế.',
  questionsTitle: 'Hỏi rõ. Hiểu đúng.',
  closeTitle: 'Việc mỗi ngày. Góc nhìn của bạn.',
  apkMissing: 'APK chưa được phát hành. Bạn có thể thử luồng thu thập trong bản demo ngay trên trang này.',
  apkDownload: 'Tải APK', partners: 'Nền tảng bởi VNG PT Lab. Camera Ego và hoạt động duyệt bởi PaXini.',
  footerNote: 'Thanh toán dựa trên số phút hữu ích đã được duyệt và chấp nhận.',
};
type Copy = Record<keyof typeof vi, string>;
const en: Copy = {
  ...DISCOVER_HELP_COPY.en,
  ...DISCOVER_WARM_COPY.en,
  activityKitchen: 'Preparing a meal', activityClothes: 'Arranging clothes', activityPacking: 'Packing an order', overlapShort: 'Shared span',
  slogan: 'Everyday skills. A new perspective.', heroA: 'Your everyday.', heroB: 'A new perspective.',
  heroBody: 'Record everyday activity with Ego. Earn for effective minutes reviewed and approved by a person.',
  explore: 'Explore the demo', console: 'Sign in to the console', skip: 'Skip the opening', scroll: 'Scroll to explore',
  menu: 'Open menu', close: 'Close menu', navigation: 'Navigation', work: 'The work', demo: 'Try the app', camera: 'The camera', review: 'Review & payment', questions: 'Questions',
  play: 'Play video', pause: 'Pause video', filmLabel: 'Illustrative film · external view, not footage recorded by Ego', filmError: 'The video could not load. You can still explore the demo below.',
  introTitle: 'Everyday work. Your perspective.', introBody: 'PlayerOne connects collectors in Vietnam with tasks to record everyday activity. VNG PT Lab builds the platform; PaXini provides the Ego camera and reviews the data.',
  demoTitle: 'Your day. A new perspective.', demoBody: 'Explore choosing a task and preparing a collection session. Recording starts with the button on the camera — never on your phone.',
  example: 'Interactive demo · illustrative data', exampleNote: 'This demo makes no real claim, collection session or recording.',
  browse: 'Choose a task', details: 'Task details', prepare: 'Prepare a session', ready: 'Ready with Ego',
  taskKitchen: 'Arrange clothes', taskDesk: 'Organise a desk', taskShelf: 'Arrange a shop shelf', home: 'At home', office: 'Office', shop: 'Shop',
  preview: 'Activity example', tryClothes: 'Try the clothes task', previewNote: 'The interactive example follows arranging clothes. This activity is a browse-only preview.',
  taskHint: 'View instructions', taskDescription: 'Work as you normally would. Read the task-specific boundaries and reminders before claiming.',
  natural: 'Natural everyday activity', hands: 'Keep the action in frame', boundaries: 'Follow the task instructions and boundaries', prerequisites: 'To claim real tasks: complete the agreements, training and exam first.',
  claim: 'Try claiming this task', claimed: 'Illustrative task selected', device: 'Device for this session', deviceExample: 'Ego · illustrative bound device', scenario: 'Scenario',
  others: 'Might other people appear in frame?', sensitive: 'Might sensitive information appear?', choose: 'Choose an answer', yes: 'Yes', no: 'No',
  prepareAction: 'Prepare the example session', physical: 'Start recording with the button on Ego.', physicalBody: 'Wear the camera on your forehead, with both eyes unobstructed. The app prepares the session; the camera button controls recording.',
  viewpoint: 'Explore the first-person view', back: 'Back', restart: 'Try another task', povLabel: 'AI-generated first-person view · illustration', povAlt: 'Hands doing everyday work from a first-person perspective',
  workTitle: 'Our collectors.', workBody: 'At home, in an office, a shop or a warehouse. Each recording belongs to a claimed task and its specific instructions.',
  imageLabel: 'AI-generated illustrations, not actual collectors or collected data.', aiLabel: 'AI illustration', imageWide: 'A person doing everyday work in daylight', imagePortrait: 'A person working naturally with a forehead-mounted camera', imageDetail: 'Hands and ordinary objects at work',
  cameraTitle: 'On your forehead. Eyes wide open.', cameraBody: 'The platform supplies Ego and binds it to one person. Its physical buttons start and stop recording. After collection, hand in the memory card at an upload centre.',
  deviceMediaNote: 'The device illustration is being corrected to show the camera properly mounted on the forehead.', deviceMediaLabel: 'Illustrative device film',
  humanTitle: 'Real work. Human judgment.', humanBody: 'A reviewer watches each recording, identifies the usable part and records reasons for the rest. Recorded time does not automatically become paid time.',
  reviewExample: 'Illustration of review outcomes', good: 'Good', partial: 'Partial', reject: 'Reject', goodBody: 'Reviewed and approved footage contributes to effective minutes.', partialBody: 'Only the reviewed and approved portion counts; the remainder has a reason.', rejectBody: 'Unapproved footage is not paid; the collector can see the reason.',
  paymentTitle: 'Paid for approved effective minutes.', paymentBody: 'Measured media time is the span covered by every recorded stream together. A human review then determines the approved effective minutes used for payment at the task’s rate.',
  streamVideo: 'Video', streamAudio: 'Audio', streamMotion: 'Motion', overlap: 'The span every stream covers together', diagram: 'Illustration only; no real duration or payment is shown.',
  questionsTitle: 'Good questions. Clear answers.', closeTitle: 'Everyday work. Your perspective.', apkMissing: 'The APK is not released yet. Try the collection flow in the demo on this page.', apkDownload: 'Download the APK', partners: 'Platform by VNG PT Lab. Ego camera and data review by PaXini.', footerNote: 'Payment is based on reviewed, approved effective minutes.',
};
const zh: Copy = {
  ...DISCOVER_HELP_COPY.zh,
  ...DISCOVER_WARM_COPY.zh,
  activityKitchen: '准备餐食', activityClothes: '整理衣物', activityPacking: '打包订单', overlapShort: '共同区间',
  slogan: '日常技能，新的视角。', heroA: '你的日常。', heroB: '新的视角。', heroBody: '用 Ego 记录日常活动。根据人工审核并认可的有效分钟获得报酬。',
  explore: '体验演示', console: '登录控制台', skip: '跳过开场', scroll: '向下滚动探索', menu: '打开菜单', close: '关闭菜单', navigation: '导航', work: '采集活动', demo: '体验应用', camera: 'Ego 相机', review: '审核与付款', questions: '常见问题',
  play: '播放视频', pause: '暂停视频', filmLabel: '示意影片 · 外部视角，并非 Ego 拍摄的画面', filmError: '视频暂时无法加载。你仍可体验下方演示。',
  introTitle: '日常工作，你的视角。', introBody: 'PlayerOne 为越南采集员提供日常活动拍摄任务。VNG PT Lab 构建平台；PaXini 提供 Ego 相机并审核数据。',
  demoTitle: '你的日常，新的视角。', demoBody: '体验选择任务并准备采集会话的流程。录制由相机上的按钮启动，而非手机。',
  example: '交互演示 · 示例数据', exampleNote: '演示不会领取真实任务、创建真实会话或开始录制。',
  browse: '选择任务', details: '任务详情', prepare: '准备采集会话', ready: '准备使用 Ego', taskKitchen: '整理衣物', taskDesk: '整理办公桌', taskShelf: '整理店铺货架', home: '居家', office: '办公室', shop: '店铺',
  preview: '活动示例', tryClothes: '体验整理衣物任务', previewNote: '交互示例演示整理衣物。此活动仅供浏览参考。',
  taskHint: '查看说明', taskDescription: '像平时一样工作。领取前请阅读具体任务的范围和注意事项。', natural: '自然的日常活动', hands: '让操作保持在画面内', boundaries: '遵守任务说明与范围', prerequisites: '领取真实任务前，需要完成协议、培训并通过考试。',
  claim: '尝试领取此任务', claimed: '已选择示例任务', device: '本次会话设备', deviceExample: 'Ego · 已绑定设备示例', scenario: '场景', others: '画面中可能出现其他人吗？', sensitive: '画面中可能出现敏感信息吗？', choose: '请选择', yes: '是', no: '否',
  prepareAction: '准备示例会话', physical: '按下 Ego 上的按钮开始录制。', physicalBody: '将相机佩戴在额头，保持双眼无遮挡。应用仅准备会话；相机按钮控制录制。', viewpoint: '探索第一人称视角', back: '返回', restart: '尝试其他任务', povLabel: 'AI 生成的第一人称视角 · 示意', povAlt: '第一人称视角下双手进行日常工作',
  workTitle: '我们的采集员。', workBody: '居家、办公室、店铺或仓库。每次录制都对应已领取的任务及其具体说明。', imageLabel: 'AI 生成的示意图，非真实采集员或采集数据。', aiLabel: 'AI 示意图', imageWide: '一人在日光下进行日常工作', imagePortrait: '额头佩戴相机的人自然地工作', imageDetail: '工作中的双手和日常物品',
  cameraTitle: '佩戴在额头，双眼无遮挡。', cameraBody: '平台提供 Ego 并绑定到一名采集员。设备上的实体按钮控制录制。采集后，将存储卡交到上传中心。', deviceMediaNote: '设备示意影片正在修正，以正确展示额头佩戴位置。', deviceMediaLabel: '设备示意影片',
  humanTitle: '真实工作，人工审核。', humanBody: '审核员查看每段记录，确定可用部分，并记录其他部分的问题原因。录制时间不会自动变成付费时间。', reviewExample: '审核结果示例', good: '通过', partial: '部分通过', reject: '不通过', goodBody: '人工审核并认可的部分计入有效分钟。', partialBody: '仅审核并认可的部分计入；其他部分会说明原因。', rejectBody: '未被认可的部分不计报酬；采集员可查看原因。',
  paymentTitle: '按认可的有效分钟支付。', paymentBody: '媒体测量时间是所有录制数据流共同覆盖的区间。随后由人工审核确定认可的有效分钟，按任务单价计算报酬。', streamVideo: '视频', streamAudio: '音频', streamMotion: '运动', overlap: '所有数据流共同覆盖的区间', diagram: '仅为示意，不展示实际时长或金额。',
  questionsTitle: '有疑问，就有解答。', closeTitle: '日常工作，你的视角。', apkMissing: 'APK 尚未发布。你可以在本页体验采集流程演示。', apkDownload: '下载 APK', partners: '平台由 VNG PT Lab 构建。Ego 相机与数据审核由 PaXini 提供。', footerNote: '报酬根据人工审核并认可的有效分钟计算。',
};
export const DISCOVER_COPY = {vi, en, zh} as const;
export type DiscoverCopy = Copy;
