const en={
  engineeringProbe:'Sample contract check',engineeringProbeNote:'Run fixed synthetic checks against the real record contract. This does not test external services or execute the pipeline.',engineeringRunProbe:'Run sample check',engineeringProbePassed:'Passed',engineeringProbeFailed:'Failed',
  engineering:'Engineering',engineeringNote:'Inspect pipeline records and service configuration. Administrator access; read-only diagnostics.',engineeringReadOnly:'Read only',engineeringRestricted:'Administrator access required',engineeringRestrictedBody:'This screen is available to active administrators. Service checks and episode records are protected by the server.',
  engineeringServices:'Services & configuration',engineeringServicesNote:'A configured integration is not proof that its external service works. Each state describes the check actually performed.',engineeringChecked:'Checked {{time}}',engineeringSecurity:'Runtime safeguards',engineeringRls:'Showcase row-level security',engineeringBypass:'Runtime bypasses row-level security',engineeringTrue:'Yes',engineeringFalse:'No',
  engineeringHealthy:'Check passed',engineeringConfigured:'Configured · not probed',engineeringUnconfigured:'Not configured',engineeringManual:'Manual operation',engineeringAvailable:'Available',engineeringUnknown:'Unknown',
  engineeringEpisodes:'Recent episodes',engineeringEpisodesNote:'Inspect an episode without starting ingestion, review or payment.',engineeringEpisodeId:'Episode UUID',engineeringLookup:'Inspect episode',engineeringClear:'Clear selection',engineeringInvalid:'Enter a complete episode UUID.',engineeringEmptyEpisodes:'No episode records were returned.',engineeringLastSeen:'Last seen',engineeringResolution:'Resolution',engineeringVerification:'Verification',engineeringUploadPath:'Upload path',engineeringIngests:'Ingest records',engineeringInspect:'Inspect',engineeringPrevious:'Previous page',engineeringNext:'Next page',
  engineeringDetail:'Episode inspection',engineeringSelect:'Choose an episode above or enter its UUID to inspect the server’s redacted record.',engineeringRecord:'Redacted record JSON',engineeringRecordNote:'Credentials, paths and other protected fields are omitted by the server. This is an inspection view, not the original source file.',engineeringNoRecord:'No record JSON is available for this episode.',engineeringIngest:'Allowlisted ingest metadata',
  engineeringAudit:'Audit metadata',engineeringAuditNote:'Stored audit event metadata only, not service logs. Payloads are omitted.',engineeringAuditSelected:'Direct episode audit events only; excludes events targeting reviews or other records.',engineeringAuditAll:'Showing recent permitted events.',engineeringEmptyAudit:'No audit events were returned.',engineeringAction:'Action',engineeringTarget:'Target',engineeringActor:'Actor role',engineeringTime:'Time',engineeringRequestRef:'Request reference',engineeringNotFound:'This episode was not found.',engineeringRedacted:'Redacted by server',
  pageTour:'Tour this page',pageTourLabel:'Tour this page — {{page}}',tourPageOverview:'This page shows your available workspace tools. Navigation and actions follow your account’s permissions.',tourProfile:'Your identity is read-only. Appearance, language and avatar preferences apply to this browser; sign out ends its session.',tourShowcase:'Demo studio keeps its test uploads and review decisions separate from production review and payments. Follow the on-page storage and deletion information.',tourEngineeringServices:'These states report the checks actually performed. Configured but unprobed services have not been verified end to end.',tourEngineeringEpisodes:'Select a recent episode or enter its UUID. The inspector shows only redacted server records; it does not run the pipeline.',tourEngineeringAudit:'Audit entries identify recorded actions and targets. Payloads are intentionally omitted.',tourPreflight:'Inspect the current preflight and its reasons before using payment actions. A preflight can expire or become invalid when the batch changes.',tourBill:'This bill preserves the server’s stored amounts, review lines and payment status. Payment controls remain subject to finance permissions and preflight.',tourExceptions:'Inspect recorded payout exceptions and their available resolutions. An unknown or refused state is not a successful payment.',
};
type Copy=Record<keyof typeof en,string>;
const vi:Copy={
  engineeringProbe:'Kiểm tra hợp đồng dữ liệu mẫu',engineeringProbeNote:'Chạy kiểm tra cố định với dữ liệu tổng hợp theo hợp đồng bản ghi thật. Không kiểm tra dịch vụ bên ngoài hay chạy pipeline.',engineeringRunProbe:'Chạy kiểm tra mẫu',engineeringProbePassed:'Đạt',engineeringProbeFailed:'Không đạt',
  engineering:'Kỹ thuật',engineeringNote:'Kiểm tra bản ghi pipeline và cấu hình dịch vụ. Chỉ quản trị viên; chẩn đoán chỉ đọc.',engineeringReadOnly:'Chỉ đọc',engineeringRestricted:'Cần quyền quản trị viên',engineeringRestrictedBody:'Màn hình này dành cho quản trị viên đang hoạt động. Máy chủ bảo vệ các kiểm tra dịch vụ và bản ghi tập.',
  engineeringServices:'Dịch vụ & cấu hình',engineeringServicesNote:'Có cấu hình không đồng nghĩa dịch vụ bên ngoài hoạt động. Mỗi trạng thái mô tả đúng kiểm tra đã thực hiện.',engineeringChecked:'Đã kiểm tra lúc {{time}}',engineeringSecurity:'Bảo vệ khi vận hành',engineeringRls:'Bảo mật theo hàng của Demo studio',engineeringBypass:'Tài khoản vận hành bỏ qua bảo mật theo hàng',engineeringTrue:'Có',engineeringFalse:'Không',
  engineeringHealthy:'Kiểm tra đạt',engineeringConfigured:'Đã cấu hình · chưa kiểm tra kết nối',engineeringUnconfigured:'Chưa cấu hình',engineeringManual:'Vận hành thủ công',engineeringAvailable:'Có sẵn',engineeringUnknown:'Chưa rõ',
  engineeringEpisodes:'Các tập gần đây',engineeringEpisodesNote:'Kiểm tra một tập mà không khởi chạy nhập dữ liệu, duyệt hay thanh toán.',engineeringEpisodeId:'UUID của tập',engineeringLookup:'Kiểm tra tập',engineeringClear:'Bỏ chọn',engineeringInvalid:'Nhập đầy đủ UUID của tập.',engineeringEmptyEpisodes:'Không có bản ghi tập được trả về.',engineeringLastSeen:'Ghi nhận gần nhất',engineeringResolution:'Phân giải',engineeringVerification:'Xác minh',engineeringUploadPath:'Đường tải lên',engineeringIngests:'Bản ghi nhập',engineeringInspect:'Kiểm tra',engineeringPrevious:'Trang trước',engineeringNext:'Trang sau',
  engineeringDetail:'Kiểm tra tập',engineeringSelect:'Chọn tập phía trên hoặc nhập UUID để xem bản ghi đã lược bỏ thông tin nhạy cảm từ máy chủ.',engineeringRecord:'JSON bản ghi đã lược bỏ',engineeringRecordNote:'Máy chủ loại bỏ thông tin xác thực, đường dẫn và các trường được bảo vệ. Đây là chế độ kiểm tra, không phải tệp nguồn gốc.',engineeringNoRecord:'Không có JSON bản ghi cho tập này.',engineeringIngest:'Thông tin nhập được phép hiển thị',
  engineeringAudit:'Thông tin nhật ký',engineeringAuditNote:'Chỉ thông tin sự kiện kiểm toán đã lưu, không phải nhật ký dịch vụ. Không hiển thị nội dung chi tiết.',engineeringAuditSelected:'Chỉ sự kiện có đối tượng trực tiếp là tập này; không gồm sự kiện của bản duyệt hay bản ghi khác.',engineeringAuditAll:'Các sự kiện gần đây được phép xem.',engineeringEmptyAudit:'Không có sự kiện nhật ký được trả về.',engineeringAction:'Thao tác',engineeringTarget:'Đối tượng',engineeringActor:'Vai trò thực hiện',engineeringTime:'Thời gian',engineeringRequestRef:'Mã tham chiếu yêu cầu',engineeringNotFound:'Không tìm thấy tập này.',engineeringRedacted:'Máy chủ đã lược bỏ thông tin',
  pageTour:'Hướng dẫn trang này',pageTourLabel:'Hướng dẫn trang này — {{page}}',tourPageOverview:'Trang này hiển thị các công cụ làm việc hiện có. Điều hướng và thao tác tuân theo quyền của tài khoản.',tourProfile:'Thông tin danh tính chỉ đọc. Giao diện, ngôn ngữ và ảnh đại diện áp dụng cho trình duyệt này; đăng xuất kết thúc phiên.',tourShowcase:'Demo studio tách bản tải lên thử và quyết định duyệt thử khỏi quy trình duyệt và thanh toán thật. Xem thông tin lưu trữ và xoá trên trang.',tourEngineeringServices:'Các trạng thái mô tả kiểm tra đã thực hiện. Dịch vụ đã cấu hình nhưng chưa kiểm tra kết nối chưa được xác minh toàn trình.',tourEngineeringEpisodes:'Chọn một tập gần đây hoặc nhập UUID. Trình kiểm tra chỉ hiển thị bản ghi đã lược bỏ từ máy chủ; không chạy pipeline.',tourEngineeringAudit:'Nhật ký xác định thao tác và đối tượng đã ghi nhận. Nội dung chi tiết được lược bỏ có chủ đích.',tourPreflight:'Xem kết quả kiểm tra trước thanh toán và lý do trước khi dùng thao tác thanh toán. Kết quả có thể hết hạn hoặc mất hiệu lực khi lô thay đổi.',tourBill:'Hoá đơn giữ nguyên số tiền lưu trên máy chủ, các dòng duyệt và trạng thái thanh toán. Thao tác thanh toán vẫn cần quyền tài chính và kiểm tra trước.',tourExceptions:'Xem các ngoại lệ thanh toán đã ghi nhận và cách xử lý hiện có. Trạng thái chưa rõ hoặc bị từ chối không phải thanh toán thành công.',
};
const zh:Copy={
  engineeringProbe:'样本契约检查',engineeringProbeNote:'使用固定合成数据检查实际记录契约，不测试外部服务，也不执行流水线。',engineeringRunProbe:'运行样本检查',engineeringProbePassed:'通过',engineeringProbeFailed:'未通过',
  engineering:'工程诊断',engineeringNote:'检查流水线记录与服务配置。仅管理员可访问；所有诊断均为只读。',engineeringReadOnly:'只读',engineeringRestricted:'需要管理员权限',engineeringRestrictedBody:'仅活跃管理员可使用此页面。服务检查和片段记录由服务器保护。',
  engineeringServices:'服务与配置',engineeringServicesNote:'已配置不代表外部服务可用。每个状态仅说明实际执行的检查。',engineeringChecked:'检查时间 {{time}}',engineeringSecurity:'运行时保护',engineeringRls:'演示工作室行级安全',engineeringBypass:'运行账户绕过行级安全',engineeringTrue:'是',engineeringFalse:'否',
  engineeringHealthy:'检查通过',engineeringConfigured:'已配置 · 未探测',engineeringUnconfigured:'未配置',engineeringManual:'人工操作',engineeringAvailable:'可用',engineeringUnknown:'未知',
  engineeringEpisodes:'最近片段',engineeringEpisodesNote:'检查片段，不启动导入、审核或付款。',engineeringEpisodeId:'片段 UUID',engineeringLookup:'检查片段',engineeringClear:'清除选择',engineeringInvalid:'请输入完整的片段 UUID。',engineeringEmptyEpisodes:'未返回片段记录。',engineeringLastSeen:'最近记录',engineeringResolution:'解析状态',engineeringVerification:'验证状态',engineeringUploadPath:'上传路径',engineeringIngests:'导入记录',engineeringInspect:'检查',engineeringPrevious:'上一页',engineeringNext:'下一页',
  engineeringDetail:'片段检查',engineeringSelect:'选择上方片段或输入 UUID，查看服务器脱敏记录。',engineeringRecord:'脱敏记录 JSON',engineeringRecordNote:'服务器省略凭据、路径及其他受保护字段。此视图用于检查，并非原始文件。',engineeringNoRecord:'此片段没有可用的记录 JSON。',engineeringIngest:'允许显示的导入元数据',
  engineeringAudit:'审计元数据',engineeringAuditNote:'仅显示已存储审计事件元数据，不含服务日志，省略载荷。',engineeringAuditSelected:'仅显示直接针对该片段的事件，不含针对审核或其他记录的事件。',engineeringAuditAll:'显示最近允许查看的事件。',engineeringEmptyAudit:'未返回审计事件。',engineeringAction:'操作',engineeringTarget:'目标',engineeringActor:'执行者角色',engineeringTime:'时间',engineeringRequestRef:'请求参考号',engineeringNotFound:'未找到此片段。',engineeringRedacted:'服务器已脱敏',
  pageTour:'浏览本页指南',pageTourLabel:'浏览本页指南 — {{page}}',tourPageOverview:'本页显示可用的工作工具。导航与操作遵循账户权限。',tourProfile:'身份信息为只读。外观、语言和头像仅适用于此浏览器；退出将结束会话。',tourShowcase:'演示工作室将测试上传和审核决定与正式审核及付款分开。请查看页面上的存储和删除说明。',tourEngineeringServices:'这些状态说明实际完成的检查。已配置但未探测的服务尚未通过端到端验证。',tourEngineeringEpisodes:'选择最近片段或输入 UUID。检查器只显示服务器脱敏记录，不运行流水线。',tourEngineeringAudit:'审计条目标明已记录的操作与目标，有意省略载荷。',tourPreflight:'付款前先查看预检结果与原因。预检可能过期，或因批次变化而失效。',tourBill:'此账单保留服务器存储金额、审核明细与付款状态。付款仍受财务权限及预检约束。',tourExceptions:'查看已记录的付款异常及可用处理方式。未知或拒绝状态不代表付款成功。',
};
export const ENGINEERING_COPY={en,vi,zh};
