import { describe, expect, it } from 'vitest';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { cp, mkdtemp, readFile, readdir, rm, stat, writeFile } from 'node:fs/promises';
import { ingest } from '../src/ingest.ts';
import { openHashCache } from '../src/hash.ts';
import { discover } from '../src/discover.ts';
import { readManifest } from '../src/manifest.ts';
import { computeTiming, readStreams } from '../src/timing.ts';
import { hasSession, session } from './sessions.ts';

/** fixtures/sessions/<label>/<session dir>. Generated by scripts/make-fixtures.ts. */
const FIXTURES = join(import.meta.dirname, '..', '..', '..', 'fixtures', 'sessions');

async function fixture(label: string): Promise<string> {
  const dir = join(FIXTURES, label);
  const [only] = await readdir(dir);
  return join(dir, only!);
}

async function withCache<T>(fn: () => Promise<T>): Promise<T> {
  const dir = await mkdtemp(join(tmpdir(), 'px-cache-'));
  const previous = process.env['PLAYERONE_CACHE'];
  process.env['PLAYERONE_CACHE'] = dir;
  try {
    return await fn();
  } finally {
    if (previous === undefined) delete process.env['PLAYERONE_CACHE'];
    else process.env['PLAYERONE_CACHE'] = previous;
    await rm(dir, { recursive: true, force: true });
  }
}

const codes = (r: Awaited<ReturnType<typeof ingest>>) => r.discrepancies.map((x) => x.code);

// ---------------------------------------------------------------------------
// B13-B20, synthetic

describe('B13 multi-part assembly', () => {
  it('three parts become one episode in timestamp order', async () => {
    const r = await withCache(async () => ingest(await fixture('multipart')));
    expect(r.streams.find((s) => s.role === 'camera_left')?.parts).toHaveLength(3);
    expect(r.streams.find((s) => s.role === 'camera_left')?.sample_count).toBe(60);
    expect(codes(r)).not.toContain('PART-GAP');
    expect(codes(r)).not.toContain('PART-ORDER-CONFLICT');
    expect(r.timing.raw_duration_s).toBeCloseTo(1.963, 2);
  });
});

describe('B14 part numbers that contradict the timestamps', () => {
  it('assembles by PTS and flags the conflict', async () => {
    const r = await withCache(async () => ingest(await fixture('reversed-parts')));
    expect(codes(r)).toContain('PART-ORDER-CONFLICT');
    expect(r.state).toBe('flagged');
    // Same coverage as the correctly numbered session, because PTS decided.
    expect(r.timing.raw_duration_s).toBeCloseTo(1.963, 2);
  });
});

describe('B15 a part missing from the middle', () => {
  it('quarantines', async () => {
    const r = await withCache(async () => ingest(await fixture('interior-part-missing')));
    expect(codes(r)).toContain('PART-MISSING-INTERIOR');
    expect(r.state).toBe('quarantined');
  });
});

describe('a gap between parts (ING-20)', () => {
  it('is itemised and removed from the duration, never silently absorbed', async () => {
    const r = await withCache(async () => ingest(await fixture('part-gap')));
    const gap = r.discrepancies.find((x) => x.code === 'PART-GAP');
    expect(gap?.detail).toContain('1.0');
    // Coverage is 2.261 s wall to wall; one second of it holds no footage.
    expect(r.timing.raw_duration_s).toBeCloseTo(1.261, 2);
    expect(r.state).toBe('flagged');
  });
});

describe('B16 a container ffprobe cannot read', () => {
  it('quarantines without crashing and still emits a record', async () => {
    const r = await withCache(async () => ingest(await fixture('corrupt-container')));
    expect(codes(r)).toContain('MEDIA-UNREADABLE');
    expect(r.state).toBe('quarantined');
    expect(r.streams.length).toBeGreaterThan(0); // not a partial record
  });
});

describe('B17 calibration removed', () => {
  it('quarantines', async () => {
    const r = await withCache(async () => ingest(await fixture('no-calibration')));
    expect(codes(r)).toContain('CALIB-MISSING');
    expect(r.state).toBe('quarantined');
    expect(r.calibration.present).toBe(false);
  });
});

describe('B18 the same session delivered twice by different paths', () => {
  it('is one episode', async () => {
    const a = await withCache(async () => ingest(await fixture('delivery-a')));
    const b = await withCache(async () => ingest(await fixture('delivery-b')));
    expect(b.content_fingerprint).toBe(a.content_fingerprint);
    expect(b.episode_id).toBe(a.episode_id);
  });
});

describe('B19 no manifest', () => {
  it('still ingests, with identity from the directory and filenames', async () => {
    const r = await withCache(async () => ingest(await fixture('no-manifest')));
    expect(r.declared).toBeNull();
    expect(r.device.serial).toBe('SYNTH0000001');
    expect(r.timing.raw_duration_s).toBeGreaterThan(0);
    expect(r.state).toBe('ok');
  });
});

describe('B20 an unknown firmware string', () => {
  it('ingests and flags', async () => {
    const r = await withCache(async () => ingest(await fixture('unknown-firmware')));
    expect(codes(r)).toContain('FIRMWARE-UNKNOWN');
    expect(r.state).toBe('flagged');
    expect(r.device.firmware_declared).toBe('9.9.9-unreleased');
  });
});

// ---------------------------------------------------------------------------
// B5, B12 and B25 against the real sessions

describe.skipIf(!hasSession('072310'))('B5 the manifest files block is never used', () => {
  it('corrupting it changes nothing in the output', async () => {
    const root = await mkdtemp(join(tmpdir(), 'px-b5-'));
    const copy = join(root, 'ego_AZER76400FE_20260813_072310');
    await cp(session('072310'), copy, { recursive: true });
    const before = await withCache(() => ingest(copy));

    const manifestPath = join(copy, 'meta_ego_AZER76400FE_20260813_072310.json');
    const parsed = JSON.parse(await readFile(manifestPath, 'utf8'));
    parsed.files = { video_left: 'nonsense.mp4', audio: 'also_nonsense.wav' };
    await writeFile(manifestPath, JSON.stringify(parsed, null, 2));
    const after = await withCache(() => ingest(copy));

    expect(after.timing.raw_duration_s).toBe(before.timing.raw_duration_s);
    expect(after.streams.map((s) => s.role)).toEqual(before.streams.map((s) => s.role));
    expect(after.content_fingerprint).toBe(before.content_fingerprint);
    await rm(root, { recursive: true, force: true });
  });
});

describe.skipIf(!hasSession('072310'))('B12 measured-to-declared ratios', () => {
  it('072310 and 072516 both inflate by about 1.5x', async () => {
    for (const [id, want] of [
      ['072310', 1.51],
      ['072516', 1.52],
    ] as const) {
      if (!hasSession(id)) continue;
      const d = await discover(session(id));
      const m = await readManifest(
        d.entries.find((e) => e.kind === 'manifest')!.path,
        new Set(d.entries.map((e) => e.file)),
      );
      const t = computeTiming(await readStreams(d.entries), m.declared);
      expect(m.declared.duration_sec! / t.rawDurationS).toBeCloseTo(want, 1);
    }
  });
});

describe.skipIf(!hasSession('072310'))('B25 resume after an interrupted run', () => {
  it('re-hashes only what was not finished, and lands on the same record', async () => {
    const cacheDir = await mkdtemp(join(tmpdir(), 'px-cache-'));
    const previous = process.env['PLAYERONE_CACHE'];
    process.env['PLAYERONE_CACHE'] = cacheDir;
    try {
      const uninterrupted = await ingest(session('072310'));

      // Simulate a kill part-way through hashing: keep half the digests, drop the rest.
      const cacheFile = join(cacheDir, 'hashes.json');
      const all = JSON.parse(await readFile(cacheFile, 'utf8')) as Record<string, string>;
      const keys = Object.keys(all).sort();
      const half = Object.fromEntries(keys.slice(0, Math.floor(keys.length / 2)).map((k) => [k, all[k]!]));
      await writeFile(cacheFile, JSON.stringify(half));

      const cache = await openHashCache();
      for (const path of [
        ...(await readdir(session('072310'))).map((n) => join(session('072310'), n)),
      ]) {
        const st = await stat(path);
        if (st.isFile()) await cache.hash(path, st.size, st.mtimeMs);
      }
      expect(cache.reused).toBe(Object.keys(half).length);
      expect(cache.computed).toBeGreaterThan(0);

      const resumed = await ingest(session('072310'));
      const strip = (r: typeof resumed) =>
        JSON.stringify({ ...r, source: { ...r.source, ingested_at: '', ingest_host: '' } });
      expect(strip(resumed)).toBe(strip(uninterrupted));
    } finally {
      if (previous === undefined) delete process.env['PLAYERONE_CACHE'];
      else process.env['PLAYERONE_CACHE'] = previous;
      await rm(cacheDir, { recursive: true, force: true });
    }
  });
});

describe.skipIf(!hasSession('072538'))('B16 a genuinely truncated MP4', () => {
  it('is caught by the packet count, not the declared duration, and quarantines', async () => {
    const root = await mkdtemp(join(tmpdir(), 'px-b16-'));
    const copy = join(root, 'ego_AZER76400FE_20260813_072538');
    await cp(session('072538'), copy, { recursive: true });

    const video = join(copy, 'ego_AZER76400FE_20260813_072538_camera_left_part0001.mp4');
    const whole = await readFile(video);
    await writeFile(video, whole.subarray(0, Math.floor(whole.length * 0.45)));

    const r = await withCache(() => ingest(copy));
    expect(codes(r)).toContain('MEDIA-UNREADABLE');
    expect(r.state).toBe('quarantined');
    expect(r.streams.find((s) => s.role === 'camera_left')?.pts_source).toBe('absent');
    // The undamaged eye is still described, so a reviewer sees what survived.
    expect(r.streams.find((s) => s.role === 'camera_right')?.sample_count).toBe(630);

    await rm(root, { recursive: true, force: true });
  });

  it('the intact container agrees with its own sidecar, packet for packet', async () => {
    // 072310 has both, so the container count and the sidecar count can be compared.
    const { probeContainer } = await import('../src/timing.ts');
    const probe = await probeContainer(
      join(session('072310'), 'ego_AZER76400FE_20260813_072310_camera_left_part0001.mp4'),
    );
    expect(probe?.packets).toBe(256);
  });
});

/**
 * Every finding this project made came from the real sample sessions, which are
 * not committed. Without a fixture for each, CI proves none of them.
 */
describe('the defect taxonomy is reachable from committed fixtures alone', () => {
  const expected: [string, string, string][] = [
    ['empty-streams', 'PTS-EMPTY', 'quarantined'],
    ['no-media', 'MEDIA-MISSING', 'quarantined'],
    ['truncated-sidecar', 'PTS-TRUNCATED', 'flagged'],
    ['clock-fault', 'STREAM-CLOCK-FAULT', 'flagged'],
    ['inflated-manifest', 'DUR-MANIFEST-INFLATED', 'flagged'],
    ['inflated-manifest', 'FRAMECOUNT-MISMATCH', 'flagged'],
    ['zeroed-stats', 'STATS-ZEROED', 'flagged'],
    ['stale-stats', 'STATS-STALE', 'flagged'],
    ['missing-tail-part', 'PART-MISSING-TAIL', 'flagged'],
    ['high-skew', 'STREAM-SKEW-HIGH', 'flagged'],
    ['imu-rate-anomaly', 'IMU-RATE-ANOMALY', 'flagged'],
  ];

  for (const [label, code, state] of expected) {
    it(`${label} raises ${code}`, async () => {
      const r = await withCache(async () => ingest(await fixture(label)));
      expect(codes(r)).toContain(code);
      expect(r.state).toBe(state);
    });
  }

  it('a stream with a broken clock costs the episode a flag, not its duration', async () => {
    const r = await withCache(async () => ingest(await fixture('clock-fault')));
    // Before the clock check, the bogus IMU start became the usable start and
    // this read 0.000 s for a session holding real video.
    expect(r.timing.raw_duration_s).toBeGreaterThan(0.5);
    expect(r.streams.find((s) => s.role === 'imu_accel')?.span_s).toBeGreaterThan(1e6);
  });

  it('a cut sidecar stops setting the end, so the cameras decide', async () => {
    const cut = await withCache(async () => ingest(await fixture('truncated-sidecar')));
    const whole = await withCache(async () => ingest(await fixture('delivery-a')));
    expect(cut.timing.raw_duration_s).toBeGreaterThan(whole.timing.raw_duration_s);
    expect(cut.timing.raw_duration_s).toBeCloseTo(0.633, 3);
  });

  it('an empty sidecar and an absent one are told apart', async () => {
    const empty = await withCache(async () => ingest(await fixture('empty-streams')));
    const absent = await withCache(async () => ingest(await fixture('corrupt-container')));
    expect(codes(empty)).toContain('PTS-EMPTY');
    expect(codes(empty)).not.toContain('PTS-ABSENT');
    expect(codes(absent)).toContain('PTS-ABSENT');
    expect(codes(absent)).not.toContain('PTS-EMPTY');
  });
});
